# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 100
    min-spare-threads: 10
  port: 80
  connection-timeout: 5000

###ThymeLeaf配置
spring:
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #编码 可不用配置
    encoding: UTF-8
    #内容类别,可不用配置
    content-type: text/html
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: WEB-INF/**

  #datasource
  datasource:
    name: local
    url: jdbc:mysql://localhost:3306/wap-project?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: wzc7336516
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=60;druid.stat.logSlowSql=true


endpoints:
  metrics:
    sensitive: false

# Mybatis-Plus 配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  typeAliasesPackage: com.kacha.wapproj.entity

logging:
  file: ./log/wap-project.log
  level:
    root: warn
    #com.kacha.wapproj: warn

management:
  address: 127.0.0.1

stat:
  aop:
    timeout: 150

